### ISSUE TITLE
Speedometer/ Arduino does not display speed or current.

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#10]
As of 4/23/2015, master branch. No lights are flashing on the CAN/USB converter.

**Comment by egtoneyUK** [comment]
This was caused by the startup scripts not being updated to the recent name changes in the program.

**Comment by cheintz** [comment]
Does the startup script now start the correct program?

**Comment by egtoneyUK** [comment]
Yeah it starts up the pi is good program and then starts the telemetry program
