### ISSUE TITLE
Time Since <startTime> resets within files

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#13]
When (in the motor controller file), the program re-writes the header information, the "Time Since" column is re-set to be relative to the NEW header's start time.

It would be much appreciated if there was also a column that was "Time Since First Header", or even something like "Time Since 0:00 Today" column. That would just make the logs easier to deal with, as we would have a column of monotonically increasing time.

To be clear, this measure of relative time is really nice to have, as is the concatenating to existing log files.

This was noticed in the 5/2/2015 motor log starting at 15-17-24. It may also exist in the battery and Arduino logs.
![capture](https://cloud.githubusercontent.com/assets/8992681/7672488/a28b6ac6-fcc2-11e4-8e5e-4a30f47f987f.PNG)
![capture](https://cloud.githubusercontent.com/assets/8992681/7672490/b94979ce-fcc2-11e4-8096-81c543a0064a.PNG)

**Comment by egtoneyUK** [comment]
This has been dealt with in the MySQL database.
