### ISSUE TITLE
Write a script that will automatically connect to an internet called 'solarcar'

### ISSUE THREAD

**Issue by egtoneyUK** [KentuckySolarCar/RaspberryPi#15]
For this project you will need to first get a list of all networks that can be found and then if one matches the specified string of 'solarcar' then force the network card to connect to that network. You will need to use BASH to do this.

**Comment by jebr224** [comment]
https://github.com/KentuckySolarCar/ad-hoc_script/blob/master/S_car.sh

**Comment by egtoneyUK** [comment]
Didn't know we had this. I'll test it and put it into the RaspberryPi Repo.
