### ISSUE TITLE
Motor controller log has wrong delimiter before bus current. Motor controller reports half the correct motor velocity. 

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#2]
(Delimiter is colon, needs to be a comma)

**Comment by cheintz** [comment]
BUMP.
This is probably the the second most important piece of information to log after speed.

**Comment by jebr224** [comment]
Well it is not the "wrong" or "right" delimiter. It is just not the delimiter you want. 
There is no specification that defines what to logs should look like (or what information is in them). 

However, I agree. The comma would be a better delimiter b/c we have already used it. Let me change it.
https://github.com/KentuckySolarCar/RaspberryPi/commit/7c9b6b4769def8f6d9f6c9aa164f2f0a61f471c4

How do you know the motor reports half the correct motor velocity. The tritium program thinks there is a extra set of poles in the motor.

If you change the 2 to a 4 that will double the recorded speed, but I question if this is necessary.
https://github.com/KentuckySolarCar/RaspberryPi/blob/7c9b6b4769def8f6d9f6c9aa164f2f0a61f471c4/SerialProg/MotorSerialIO.py#L23
 

Thank you
John Broadbent

**Comment by cheintz** [comment]
John,

I can think of no reason that the delimiter between the time and bus current should be different from the delimiter between all of the other fields.

The vehicle speed is reported correctly ( in miles per hour), but the MOTOR velocity is reported as half of the correct velocity(in revolutions per minute). This is not a *problem* as of now (We don't really use this piece of information), but it at least merits documentation. This arises from telling the Tritium motor controller (with the config utility) that there is twice as many motor poles as actually exist because doing so causes the motor to run more smoothly.

**Comment by jebr224** [comment]
https://github.com/KentuckySolarCar/RaspberryPi/commit/185895b9433ab905406351f279ea5c718156c635

**Comment by cheintz** [comment]
As of the logs on 2015-04-07\00-11-21\motor.txt, this issue still exists.

**Comment by egtoneyUK** [comment]
Is the motor velocity still incorrect?

**Comment by cheintz** [comment]
Vehicle Speed is correct, as far as I can tell from the code, motor speed
is low by a factor of 2.

Should be fixable by multiplying this line by 2:

https://github.com/KentuckySolarCar/RaspberryPi/blob/master/SerialProg/MotorSerialIO.py#L136

**Comment by egtoneyUK** [comment]
Does this now look correct?
[0085d44d02df27ac1c0c688c21875a0ea1f8f2ea](https://github.com/KentuckySolarCar/RaspberryPi/blob/development/SerialProg/MotorSerialIO.py)

**Comment by cheintz** [comment]
Looks good!
