### ISSUE TITLE
Change all log filenames to *.csv, as opposed to *.txt

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#3]

**Comment by jebr224** [comment]
Please explain why you want this? 
I assume Ethan avoided .csv extent ion b/c he was unsure it would be compatible with all .csv viewers. I suggest you rename the output file with the extinction you want. 

However, if you are destine to change it, just replace the 4 ".txt" to ".csv" in EthanSerialCode.py line 16 to 19, marked below.
https://github.com/KentuckySolarCar/RaspberryPi/blob/1560700f6e4fdc42789d5b8a9bb18ece154c3e80/SerialProg/EthanSerialCode.py#L16-L19

Thank you
John Broadbent

**Comment by egtoneyUK** [comment]
Now that everything is going to be in a database this is no longer valid.
