### ISSUE TITLE
Battery log data rate

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#5]
Log contains 5hz data, but data is sent by battery box (and changes in the log at approximately 1hz).
Battery data does not contain any header information.
Battery data appears to only contain data from one of the half packs.

All conditions have existed since on or before 2014-10-24.

**Comment by jebr224** [comment]
https://github.com/KentuckySolarCar/RaspberryPi/commit/6ba57aed26257f5a02d566584c485c283e021d26

**Comment by cheintz** [comment]
Battery data likely still only contains data from one pack.
Battery data still does not contain header (which should have units at some point)

**Comment by cheintz** [comment]
As of the log 2015-04-07\00-11-21\battery.txt, these issues still exist.

**Comment by crba233** [comment]
-Changed data log rate for batteries to 1 hz
-Battery header information added (solving the issue of only one battery pack appearing to be logged)

**Comment by cheintz** [comment]
As of logs from 2015-04-30, battery header information is not present and lack of variation in data suggests that only one pack is logged.

Furthermore, data is still written to the file with timestamps approximately every 0.2 seconds, even though it only changes about every 2 seconds.

**Comment by crba233** [comment]
This is fixed in the new code that has not been uploaded to the PI (unless Ethan did that today)
