### ISSUE TITLE
Move console logs ( created by John's autorun script) in the same folder as the data logs.

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/RaspberryPi#8]
This would be helpful because then they would be pushed to the SVN AND they would be easily related to the datafiles that the error affected.

This is not-trivial because right now, the python program (called by this script) creates the directory where the logs are stored.

Possible solution:

Have the startup script create the  and pass the path as a parameter to the python program.  Perhaps have the python program create an appropriate directory if the parameter is not present.

**Comment by egtoneyUK** [comment]
The logs are now in the /home/pi/Desktop/Logs/Error_Logs and /home/pi/Desktop/Logs/Normal_Logs
